### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by mihaierosx2** [lavaground/F1TV-Viewer#1]
Hi, I am using:

`--hls-audio-select "*"`

But for some reason I don't get any sound in VLC, what could it be? Am I doing something wrong here?

Any help is much appreciated, thank you!

**Comment by lavaground** [comment]
Hi mihaierosx2.

in VLC select one of the Audio-Streams :)

The "*" tells Streamlink to get all available Audio Streams. Sometimes (mostly replays afaik) the first stream is FX only instead of english.

**Comment by mihaierosx2** [comment]
@lavaground I figured it out that it happens because of it being a replay. So I can't select english for some replays...

**Comment by lavaground** [comment]
@mihaierosx2 It should be available, just switch through the different audio streams in VLC (usually stream 2). When you start the stream in the browser you can see the order of available languages, it should be the same order in VLC, too. Sometimes it takes a couple of seconds until audio starts. :)

**Comment by mihaierosx2** [comment]
Hmm the problem is that I don't have any audio tracks... btw I am trying to watch Australian GP 2019..
<img width="762" alt="Screenshot 2020-03-11 at 20 56 20" src="https://user-images.githubusercontent.com/14870994/76453072-d1142480-63da-11ea-86b3-92d524bab31a.png">

**Comment by lavaground** [comment]
I have all 6 Audio Tracks, Windows 10. 

Do you have audio in the browser and did you catch the first master.m3u8?
I don't know about any restrictions for your regional area.

**Comment by mihaierosx2** [comment]
@lavaground thank you very much for everything, but I figured it out by myself, it's because I am running on macOS and I don't have FFmpeg  🤦‍♂

> Required to play streams that are made up of separate audio and video streams, eg. YouTube 1080p+

**Comment by lavaground** [comment]
Oh shit, good one reading the manual and good to know, thanks. 👍
